server.port: ${PORT:8080}

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:service}
    username: ${DB_USER:service}
    password: ${DB_PASS:letmeeeen}
    driver-class-name: org.postgresql.Driver

  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    locations: classpath:migration/postgres

  kafka:
    bootstrap-servers: ${KAFKA_HOSTNAME:localhost}:${KAFKA_PORT:9092}

    producer:
      transaction-id-prefix: yt.
      properties:
        enable.idempotence: true

    consumer:
      key-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      isolation-level: read_committed
      enable-auto-commit: false
      properties:
        spring:
          json:
            trusted:
              packages: "com.pauldaniv.promotion.yellowtaxi.facade.model"
